//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMovie.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Movie
    {
        public int ID { get; set; }
        [Required, StringLength(60, MinimumLength =3)]
        public string Title { get; set; }
        [Display(Name ="Release Date"), DataType(DataType.Date)]
        [DisplayFormat(DataFormatString ="{0:d}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        [Required, StringLength(30)]
        [RegularExpression(@"^[A-Z]+[a-zA-Z'\s]*$", ErrorMessage = "Special Characters not allowed")]
        public string Genre { get; set; }
        [Range(1,100), DataType(DataType.Currency)]
        public Nullable<decimal> Price { get; set; }
    }
}
